<?php

namespace App\Http\Controllers\Staff;


use App\Http\Controllers\Controller;
use App\Models\Equipment;
use App\Models\Campus;
use App\Models\EquipmentType;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Log;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;


class EquipmentController extends Controller
{
    /**
     * Display a listing of the equipment.
     *
     * @return \Illuminate\View\View
     */
    public function index(Request $request)
    {
        $user = Auth::guard('staff')->user();

        // Start with equipment from the staff's office
        $query = Equipment::where('office_id', $user->office_id);

        // Search functionality
        if ($request->has('search')) {
            $search = $request->input('search');
            $query->where(function($q) use ($search) {
                $q->where('model_number', 'like', "%{$search}%")
                  ->orWhere('serial_number', 'like', "%{$search}%")
                  ->orWhere('description', 'like', "%{$search}%");
            });
        }

        if ($request->has('date_from') && $request->date_from) {
            $query->whereDate('created_at', '>=', $request->date_from);
        }
        if ($request->has('date_to') && $request->date_to) {
            $query->whereDate('created_at', '<=', $request->date_to);
        }

        $equipment = $query->with(['category', 'maintenanceLogs' => function($query) {
            $query->latest()->limit(5);
        }])->paginate(10);

        $equipmentTypes = $this->getEquipmentTypes();

        // Get campuses with their active offices for filter
        $campuses = \App\Models\Campus::with(['offices' => function($query) {
            $query->where('is_active', true)->orderBy('name');
        }])->orderBy('name')->get();

        // Get categories for filter
        $categories = \App\Models\Category::where('is_active', true)->orderBy('name')->pluck('name', 'id');

        return view('equipment.index', compact('equipment', 'equipmentTypes', 'campuses', 'categories'));
    }

    /**
     * Show the form for creating a new equipment.
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        $equipment = new Equipment();
        $categories = $this->getEquipmentCategories();
        $equipmentTypes = $this->getEquipmentTypes();
        $campuses = Campus::with('offices')->get();
        return view('equipment.form', compact('equipment', 'categories', 'equipmentTypes', 'campuses'));
    }

    /**
     * Store a newly created equipment in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $user = Auth::guard('staff')->user();

        $validated = $request->validate([
            'model_number' => 'required|string|max:100',
            'serial_number' => 'required|string|max:100|unique:equipment',
            'equipment_type_id' => 'required|integer|exists:equipment_types,id',
            'description' => 'nullable|string',
            'purchase_date' => 'nullable|date',
        ]);

        // Set office_id to the authenticated staff's office
        $validated['office_id'] = $user->office_id;

        // QR code will be auto-generated by the model's creating event
        $equipment = Equipment::create($validated);

        // Generate and save QR code using QRServer API with comprehensive structured data
        $qrData = json_encode([
            'id' => $equipment->id,
            'type' => 'equipment',
            'model_number' => $equipment->model_number,
            'serial_number' => $equipment->serial_number,
            'equipment_type' => $equipment->equipmentType?->name ?? 'Unknown',
            'office' => $equipment->office ? $equipment->office->name : 'N/A',
            'status' => $equipment->status,
        ]);
        $qrSize = '200x200';
        $apiUrl = "https://api.qrserver.com/v1/create-qr-code/?data=" . urlencode($qrData) . "&size={$qrSize}";

        $response = Http::get($apiUrl);
        if ($response->successful()) {
            $fileName = 'equipment_' . $equipment->id . '.png';
            $path = 'qrcodes/' . $fileName;
            Storage::disk('public')->put($path, $response->body());

            // Update equipment with QR code image path
            $equipment->update(['qr_code_image_path' => $path]);
        } else {
            Log::error('Failed to generate QR code for equipment ID: ' . $equipment->id);
        }

        return redirect()->route('staff.equipment.index')
            ->with('success', 'Equipment added successfully.');
    }

    /**
     * Display the specified equipment.
     *
     * @param  \App\Models\Equipment  $equipment
     * @return \Illuminate\View\View
     */
    public function show(Request $request, Equipment $equipment)
    {
        $user = Auth::guard('staff')->user();

        // Ensure staff can only view equipment from their office
        if ($equipment->office_id !== $user->office_id) {
            abort(403, 'You can only view equipment from your office.');
        }

        $equipment->load('office', 'equipmentType');

        // Generate QR code if missing
        if (!$equipment->qr_code) {
            $equipment->qr_code = 'EQP-' . Str::upper(Str::random(8));
            $equipment->save();
        }

        // Generate QR code image if missing
        if (!$equipment->qr_code_image_path || !Storage::disk('public')->exists($equipment->qr_code_image_path)) {
            try {
                $qrData = json_encode([
                    'id' => $equipment->id,
                    'type' => 'equipment',
                    'model_number' => $equipment->model_number,
                    'serial_number' => $equipment->serial_number,
                    'equipment_type' => $equipment->equipmentType ? $equipment->equipmentType->name : 'Unknown',
                    'office' => $equipment->office ? $equipment->office->name : 'N/A',
                    'status' => $equipment->status,
                ]);

                $qrSize = '200x200';
                $apiUrl = "https://api.qrserver.com/v1/create-qr-code/?data=" . urlencode($qrData) . "&size={$qrSize}&format=png";

                $response = Http::get($apiUrl);

                if ($response->successful()) {
                    $fileName = 'equipment_' . $equipment->id . '.png';
                    $path = 'qrcodes/' . $fileName;
                    Storage::disk('public')->put($path, $response->body());
                    $equipment->update(['qr_code_image_path' => $path]);
                }
            } catch (\Exception $e) {
                // QR code generation failed, but continue showing the page
            }
        }

        $prefix = 'staff'; // For staff routes

        if (request()->ajax()) {
            return view('equipment.show_modal', compact('equipment', 'prefix'));
        }

        return view('equipment.show_modal', compact('equipment', 'prefix'));
    }

    /**
     * Show the form for editing the specified equipment.
     *
     * @param  \App\Models\Equipment  $equipment
     * @return \Illuminate\View\View
     */
    public function edit(Equipment $equipment)
    {
        $user = Auth::guard('staff')->user();

        // Ensure staff can only edit equipment from their office
        if ($equipment->office_id !== $user->office_id) {
            abort(403, 'You can only edit equipment from your office.');
        }

        $categories = $this->getEquipmentCategories();
        $equipmentTypes = $this->getEquipmentTypes();
        $campuses = Campus::with('offices')->get();

        if (request()->ajax()) {
            // Return partial view for modal
            return view('equipment.form_modal', compact('equipment', 'categories', 'equipmentTypes', 'campuses'));
        }

        return view('equipment.form_modal', compact('equipment', 'categories', 'equipmentTypes', 'campuses'));
    }

    /**
     * Update the specified equipment in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Equipment  $equipment
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, Equipment $equipment)
    {
        $user = Auth::guard('staff')->user();

        // Ensure staff can only update equipment from their office
        if ($equipment->office_id !== $user->office_id) {
            abort(403, 'You can only update equipment from your office.');
        }

        $validated = $request->validate([
            'model_number' => 'required|string|max:100',
            'serial_number' => 'required|string|max:100|unique:equipment,serial_number,' . $equipment->id,
            'equipment_type_id' => 'required|integer|exists:equipment_types,id',
            'description' => 'nullable|string',
            'purchase_date' => 'nullable|date',
        ]);

        $equipment->update($validated);

        return redirect()->route('staff.equipment.index')
            ->with('success', 'Equipment updated successfully.');
    }

    /**
     * Remove the specified equipment from storage.
     *
     * @param  \App\Models\Equipment  $equipment
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Equipment $equipment)
    {
        $user = Auth::guard('staff')->user();

        // Ensure staff can only delete equipment from their office
        if ($equipment->office_id !== $user->office_id) {
            abort(403, 'You can only delete equipment from your office.');
        }

        $equipment->delete();

        return redirect()->route('staff.equipment.index')
            ->with('success', 'Equipment deleted successfully.');
    }

    /**
     * Update the status of the specified equipment.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Equipment  $equipment
     * @return \Illuminate\Http\JsonResponse
     */
    public function updateStatus(Request $request, Equipment $equipment)
    {
        $request->validate([
            'status' => 'required|in:available,in_use,maintenance,disposed'
        ]);

        $equipment->update([
            'status' => $request->status
        ]);

        return response()->json([
            'success' => true,
            'message' => 'Equipment status updated successfully.'
        ]);
    }

    /**
     * Process QR code scan result for Staff
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function scanQrCode(Request $request)
    {
        $request->validate([
            'qr_data' => 'required|string',
        ]);

        try {
            $qrData = json_decode($request->qr_data, true);

            if (!$qrData || !isset($qrData['id'])) {
                return response()->json([
                    'success' => false,
                    'message' => 'Invalid QR code format'
                ], 400);
            }

            $equipment = Equipment::with('office', 'equipmentType')
                ->find($qrData['id']);

            if (!$equipment) {
                return response()->json([
                    'success' => false,
                    'message' => 'Equipment not found'
                ], 404);
            }

            // Check if staff has access to this equipment (equipment from their office)
            $user = Auth::guard('staff')->user();
            if (!$equipment->office_id || $equipment->office_id !== $user->office_id) {
                return response()->json([
                    'success' => false,
                    'message' => 'You do not have access to this equipment'
                ], 403);
            }

            return response()->json([
                'success' => true,
                'equipment' => [
                    'id' => $equipment->id,
                    'model_number' => $equipment->model_number,
                    'serial_number' => $equipment->serial_number,
                    'equipment_type' => $equipment->equipmentType ? $equipment->equipmentType->name : 'Unknown',
                    'status' => $equipment->status,
                    'location' => $equipment->location,
                    'office' => $equipment->office ? $equipment->office->name : 'N/A',
                    'qr_code' => $equipment->qr_code,
                ]
            ]);

        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Error processing QR code: ' . $e->getMessage()
            ], 500);
        }
    }

    /**
     * Show the scanned equipment details view for Staff
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\View\View
     */
    public function scanView(Request $request)
    {
        return view('equipment.scan');
    }

    /**
     * Get the equipment types for the form
     *
     * @return array
     */
    protected function getEquipmentTypes()
    {
        return \App\Models\EquipmentType::where('is_active', true)->pluck('name', 'id');
    }

    /**
     * Get the equipment categories for the form
     *
     * @return array
     */
    protected function getEquipmentCategories()
    {
        return [
            'IT Equipment',
            'Audio/Visual',
            'Office Equipment',
            'Networking',
            'Medical Equipment',
            'Laboratory',
            'Industrial',
            'Lab Equipment',
            'Furniture',
            'Other'
        ];
    }

    /**
     * Show the QR code for the specified equipment.
     *
     * @param  \App\Models\Equipment  $equipment
     * @return \Illuminate\Http\Response
     */
    public function qrCode(Equipment $equipment)
    {
        $user = Auth::guard('staff')->user();

        // Ensure staff can only access QR code for equipment from their office
        if ($equipment->office_id !== $user->office_id) {
            abort(403, 'You can only access QR codes for equipment from your office.');
        }

        // If QR code image is saved, return it
        if ($equipment->qr_code_image_path && Storage::disk('public')->exists($equipment->qr_code_image_path)) {
            return response()->file(public_path('storage/' . $equipment->qr_code_image_path));
        }

        // Fallback to generating on-the-fly if no saved image
        if (!$equipment->qr_code) {
            $equipment->qr_code = 'EQP-' . Str::upper(Str::random(8));
            $equipment->save();
        }

        // Generate QR code using QRServer API
        $qrData = json_encode([
            'id' => $equipment->id,
            'type' => 'equipment',
            'model_number' => $equipment->model_number,
            'serial_number' => $equipment->serial_number,
            'equipment_type' => $equipment->equipmentType ? $equipment->equipmentType->name : 'Unknown',
            'office' => $equipment->office ? $equipment->office->name : 'N/A',
            'status' => $equipment->status,
            'url' => route('staff.equipment.show', $equipment),
            'qr_code' => $equipment->qr_code,
            'created_at' => $equipment->created_at->toISOString(),
        ]);

        $apiUrl = "https://api.qrserver.com/v1/create-qr-code/?data=" . urlencode($qrData) . "&size=300x300&format=svg";

        $response = Http::get($apiUrl);

        if ($response->successful()) {
            return response($response->body())->header('Content-Type', 'image/svg+xml');
        }

        // Fallback: return a simple text response
        return response('QR Code generation failed')->header('Content-Type', 'text/plain');
    }

    /**
     * Download the QR code for the specified equipment.
     *
     * @param  \App\Models\Equipment  $equipment
     * @return \Illuminate\Http\Response
     */
    public function downloadQrCode(Equipment $equipment)
    {
        $user = Auth::guard('staff')->user();

        // Ensure staff can only download QR code for equipment from their office
        if ($equipment->office_id !== $user->office_id) {
            abort(403, 'You can only download QR codes for equipment from your office.');
        }

        // Generate QR code if it doesn't exist
        if (!$equipment->qr_code) {
            $equipment->qr_code = 'EQP-' . Str::upper(Str::random(8));
            $equipment->save();
        }

        // Generate QR code using QRServer API
        $qrData = json_encode([
            'id' => $equipment->id,
            'type' => 'equipment',
            'model_number' => $equipment->model_number,
            'serial_number' => $equipment->serial_number,
            'equipment_type' => $equipment->equipmentType ? $equipment->equipmentType->name : 'Unknown',
            'office' => $equipment->office ? $equipment->office->name : 'N/A',
            'status' => $equipment->status,
            'url' => route('staff.equipment.show', $equipment),
            'qr_code' => $equipment->qr_code,
            'created_at' => $equipment->created_at->toISOString(),
        ]);

        $apiUrl = "https://api.qrserver.com/v1/create-qr-code/?data=" . urlencode($qrData) . "&size=300x300&format=svg";

        $response = Http::get($apiUrl);

        if ($response->successful()) {
            $filename = 'qr-code-' . Str::slug($equipment->model_number . '-' . $equipment->serial_number) . '.svg';
            return response($response->body())
                ->header('Content-Type', 'image/svg+xml')
                ->header('Content-Disposition', 'attachment; filename="' . $filename . '"');
        }

        // Fallback: return a simple text response
        return response('QR Code generation failed')->header('Content-Type', 'text/plain');
    }

    /**
     * Print the QR code for the specified equipment.
     *
     * @param  \App\Models\Equipment  $equipment
     * @return \Illuminate\Http\Response
     */
    public function printQRCode(Equipment $equipment)
    {
        $user = Auth::guard('staff')->user();

        // Ensure staff can only print QR code for equipment from their office
        if ($equipment->office_id !== $user->office_id) {
            abort(403, 'You can only print QR codes for equipment from your office.');
        }

        // Generate QR code if it doesn't exist
        if (!$equipment->qr_code) {
            $equipment->qr_code = 'EQP-' . Str::upper(Str::random(8));
            $equipment->save();
        }

        // Generate QR code using QRServer API
        $qrData = json_encode([
            'id' => $equipment->id,
            'type' => 'equipment',
            'model_number' => $equipment->model_number,
            'serial_number' => $equipment->serial_number,
            'equipment_type' => $equipment->equipmentType ? $equipment->equipmentType->name : 'Unknown',
            'office' => $equipment->office ? $equipment->office->name : 'N/A',
            'status' => $equipment->status,
            'url' => route('staff.equipment.show', $equipment),
            'qr_code' => $equipment->qr_code,
            'created_at' => $equipment->created_at->toISOString(),
        ]);

        $apiUrl = "https://api.qrserver.com/v1/create-qr-code/?data=" . urlencode($qrData) . "&size=300x300&format=svg";

        $response = Http::get($apiUrl);

        if ($response->successful()) {
            $filename = 'qr-code-' . Str::slug($equipment->model_number . '-' . $equipment->serial_number) . '.svg';
            return response($response->body())
                ->header('Content-Type', 'image/svg+xml')
                ->header('Content-Disposition', 'attachment; filename="' . $filename . '"');
        }

        // Fallback: return a simple text response
        return response('QR Code generation failed')->header('Content-Type', 'text/plain');
    }
}
